name: Build

on: [push, pull_request]

jobs:
  install_clang_macos:
    runs-on: macos-11
    steps:
    - name: Install clang++ on macOS
      run: |
        pwd
        uname -a
        brew install llvm
        /usr/local/opt/llvm/bin/clang++ --version
        export PATH="/usr/local/opt/llvm/bin:$PATH"
        export CXX=/usr/local/opt/llvm/bin/clang++
        which clang++
        clang++ --version
  install_clang_ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: Install clang++ on Ubuntu
      run: |
        pwd
        uname -a
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo bash -x ./llvm.sh 15
        export CXX=clang++-15
        which clang++-15
        clang++-15 --version
  build_wheels:
    needs: [install_clang_macos, install_clang_ubuntu]
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11 ]
        # python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: [ "3.7" ]
        compiler: [ "clang++" ]
    env:
      RUNNER_OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl