name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11 ]
        # python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: [ "3.7" ]
        compiler: [ "clang++" ]
    env:
      RUNNER_OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}


    steps:
      # install clang++
      - name: Install clang++
        run: |
          pwd
          uname -a
          [[ "${RUNNER_OS}" = "macos-11" ]] && brew install llvm && /usr/local/opt/llvm/bin/clang++ --version
          [[ "${RUNNER_OS}" = "ubuntu-20.04" ]] && wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo bash -x ./llvm.sh 15
          which clang++
          clang++ --version
      - uses: actions/checkout@v3
        # with:
        #   submodules: recursive
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl