name: Build

on: [push, pull_request]

jobs:
  build_wheels_linux:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        # python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: [ "3.7" ]
    env:
      RUNNER_OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
      - name: Install clang++ for Ubuntu
        if: matrix.os == 'ubuntu-20.04'
        run: |
          pwd
          uname -a
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 15
          which clang++-15
          clang++-15 --version
          sudo apt-get install -y cmake ccache ninja-build yasm gawk
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build wheels
        run: pip install -U pip tox && tox -e build -- --wheel --wheel-dir wheelhouse
        env:
          CIBW_ENVIRONMENT_LINUX: "CC=/usr/bin/clang-15 CXX=/usr/bin/clang++-15"
          CIBW_DEBUG: 1
          CIBW_BEFORE_BUILD: "pip install -U pip tox"
          CIBW_BUILD_VERBOSITY: 3
          # CIBW_TEST_COMMAND: "tox -e py{pyver}"
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  build_wheels_macos:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-11 ]
        # python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: [ "3.7" ]
    env:
      RUNNER_OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
      - name: Install clang++ for macOS
        if: matrix.os == 'macos-11'
        run: |
          pwd
          uname -a
          brew update
          brew install ccache cmake ninja libtool gettext llvm gcc binutils grep findutils
          export PATH=$(brew --prefix llvm)/bin:$PATH
          which clang++
          clang++ --version
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build wheels
        run: pip install -U pip tox && tox -e build -- --wheel --wheel-dir wheelhouse
        env:
          CIBW_ENVIRONMENT_MACOS: "PATH=/usr/local/opt/llvm/bin/:/usr/local/opt/grep/libexec/gnubin:/usr/local/opt/binutils/bin:$PATH:/usr/local/opt/findutils/libexec/gnubin\
             CC=$(brew --prefix llvm)/bin/clang CXX=$(brew --prefix llvm)/bin/clang++"
          CIBW_DEBUG: 1
          CIBW_BEFORE_BUILD: "pip install -U pip tox"
          CIBW_BUILD_VERBOSITY: 3
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl